apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: ghcr.io/srivastavanik/consensus-orchestrator:latest
          ports:
            - containerPort: 8000
          env:
            - name: NOVITA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: novita
                  key: api_key
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - port: 80
      targetPort: 8000

