name: docker
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: |
          docker build -f infra/docker/Dockerfile.orchestrator -t ghcr.io/${{ github.repository_owner }}/consensus-orchestrator:latest .
          docker build -f infra/docker/Dockerfile.ui -t ghcr.io/${{ github.repository_owner }}/consensus-ui:latest .
      - name: Push images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/consensus-orchestrator:latest
          docker push ghcr.io/${{ github.repository_owner }}/consensus-ui:latest

